services:
  - docker

script:
  - docker --version

# Build
- docker build -t udagram-api-feed ./udagram-api-feed
# Do similar for other three images
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t reverseproxy ./udagram-reverseproxy


# Tagging
- docker tag udagram-api-feed boujlelmanel/udagram-api-feed:v1
# Do similar for other three images
- docker tag udagram-api-user boujlelmanel/udagram-api-user:v1
- docker tag udagram-frontend boujlelmanel/udagram-frontend:v1
- docker tag reverseproxy boujlelmanel/udagram-reverseproxy:v1


# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push boujlelmanel/udagram-api-feed:v1
# Do similar for other three images
- docker push boujlelmanel/udagram-api-user:v1
- docker push boujlelmanel/udagram-frontend:v1
- docker push boujlelmanel/reverseproxy:v1

after_success:
  echo "Docker Images Built & Pushed Successfully"

 