services:
  - docker

script:
  - docker --version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Building & Tagging Docker Images
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed boujlelmanel/udagram-api-feed
  - docker tag udagram-api-user boujlelmanel/udagram-api-user
  - docker tag udagram-frontend boujlelmanel/udagram-frontend
  - docker tag reverseproxy boujlelmanel/reverseproxy
  
  - docker push boujlelmanel/udagram-api-feed
  - docker push boujlelmanel/udagram-api-user
  - docker push boujlelmanel/udagram-frontend
  - docker push boujlelmanel/reverseproxy

after_success:
  echo "Docker Images Built & Pushed Successfully"